### PR TITLE
Value inference from current variable; export fetch-value logic

### LINKED ISSUE #6: unit tests
write unit tests

### PR DESCRIPTION
**Pull request by vreuter**
The fetch-value logic of trying `getOption` and falling back to `Sys.getenv` is useful even outside this package. Also, this allows the `set` action to use the value of a current option or env. var. Close #6

### CODE REVIEW

**Comment by vreuter** [comment]
Sorry @michalstolarczyk I saw #6 and hadn't seen that you'd self assigned; there are now some tests added now but I'm sure there are still more cases that could be covered so by all means add if you had some ideas already or see spots where we could add coverage

**Comment by nsheff** [comment]
I'd rename `optOrVar` to `optOrEnvVar`.

**Comment by nsheff** [comment]
I'd rename the `currVar` argument. but can't think of something better... I just fail to connect the logic to the term `current`.

maybe `optVar`? or just `var` ? or `pathVar`. Yeah, maybe `pathVar`.

**Review by stolarczyk — APPROVED** [review]

**Comment by nsheff** [comment]
what is the meaning of `PDIR` in these?
```
.PDIROPTTAG = "FF_"
.PDIRFUNCTAG = "ff"
```

how about `FFTAGFUNC` AND `FFTAGOPT` ?

**Comment by nsheff** [comment]
can we add a unit test to confirm that we don't regress on #1 and #5 -- just check for any double-slashes or something when given variables that either do or don't have a trailing slash?

**Comment by stolarczyk** [comment]
> can we add a unit test to confirm that we don't regress on #1 and #5 -- just check for any double-slashes or something when given variables that either do or don't have a trailing slash?

I'll do it

**Comment by vreuter** [comment]
> what is the meaning of `PDIR` in these?
> 
> ```
> .PDIROPTTAG = "FF_"
> .PDIRFUNCTAG = "ff"
> ```
> 
> how about `FFTAGFUNC` AND `FFTAGOPT` ?

Maybe `PDIR` is used to mean "project dir"? I don't think that I named these, though...if I did I'm fine w/ either way...

**Review by nsheff — APPROVED** [review]
Ok ready to merge:
- [x] update NEWS.md (remove NEWS)
- [x] add you two as contributors
- [x] update vignette to document new functions/capabilities
- [ ] tag release

**Comment by nsheff** [comment]
*I think* there can be only one person with role as `cre`, others have to be `aut` or `ctb`.

Maybe related to #11 ?

**Comment by vreuter** [comment]
Ah OK, figured "cre" is "credit," but I guess it's "creator?"

**Comment by nsheff** [comment]
I think 'cre' means 'maintainer'. I'm not sure what it originally stood for, but I thought if it as creator originally...but really, it's maintainer. i think there's a bit of a disconnect there.

**Comment by vreuter** [comment]
> Are these two lines required to pass the `check`?
> 
> The [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) reads: "Both ‘Author’ and ‘Maintainer’ fields can be omitted if a suitable ‘Authors@R’ field is given."

That's correct; nonetheless, it failed previously but succeeded afterward for me.

**Comment by stolarczyk** [comment]
That's interesting. It passed the check for me without these additional lines

**Comment by vreuter** [comment]
OK well if it passes for you guys and/or on Rivanna feel free to remove them and attribute the discrepancy to something with my local machine / local R.

**Comment by nsheff** [comment]
> OK well if it passes for you guys and/or on Rivanna feel free to remove them and attribute the discrepancy to something with my local machine / local R.

Let's let travis decide.

**Comment by nsheff** [comment]
success!

**Comment by nsheff** [comment]
no authors section FTW.

**Comment by vreuter** [comment]
OK, can this be merged now?

**Comment by nsheff** [comment]
I will merge/release this today after updating the vignette to reflect the postpend changes.

**Comment by nsheff** [comment]
wow I dropped the ball on this one...

**Pull request merged**
